/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    files: File;
    'event-rooms': EventRoom;
    speakers: Speaker;
    events: Event;
    'event-registrations': EventRegistration;
    'payload-kv': PayloadKv;
    fileFolders: FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    fileFolders: {
      documentsAndFolders: 'fileFolders' | 'files';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    'event-rooms': EventRoomsSelect<false> | EventRoomsSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    fileFolders: FileFoldersSelect<false> | FileFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Quando marcado, o arquivo fica acessível publicamente sem autenticação
   */
  isPublic?: boolean | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fileFolders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'fileFolders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'files';
          value: number | File;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'files'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rooms".
 */
export interface EventRoom {
  id: number;
  /**
   * Nome identificador da sala de evento
   */
  title: string;
  /**
   * Informações adicionais sobre a sala
   */
  description?: string | null;
  /**
   * Número máximo de pessoas que a sala comporta
   */
  capacity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  /**
   * Nome completo do palestrante
   */
  name: string;
  /**
   * Título ou especialidade profissional
   */
  professionalTitle: string;
  /**
   * Informações adicionais sobre o palestrante
   */
  description?: string | null;
  /**
   * Foto de perfil do palestrante
   */
  photo?: (number | null) | File;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Nome do evento
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Informações sobre o evento
   */
  description: string;
  /**
   * Endereço completo do evento
   */
  location: string;
  /**
   * Imagem de capa do evento
   */
  image: number | File;
  /**
   * Como o evento será realizado
   */
  modality: 'in-person' | 'virtual' | 'hybrid';
  /**
   * Quem pode participar do evento
   */
  scope: 'institutional' | 'public';
  /**
   * Data de início
   */
  startDate: string;
  /**
   * Data de encerramento
   */
  endDate: string;
  /**
   * Horário de início
   */
  startTime: string;
  /**
   * Horário de encerramento
   */
  endTime: string;
  /**
   * Como serão feitas as inscrições
   */
  registrationType: 'internal' | 'external';
  /**
   * URL para inscrição externa
   */
  externalRegistrationUrl?: string | null;
  /**
   * Número máximo de inscrições
   */
  registrationLimit?: number | null;
  /**
   * Quantidade de dias para solicitar reembolso
   */
  refundDays?: number | null;
  /**
   * Data e hora de início das inscrições
   */
  registrationStart?: string | null;
  /**
   * Data e hora de encerramento das inscrições
   */
  registrationEnd?: string | null;
  /**
   * Minutos antes do evento para permitir check-in
   */
  checkinMinutesBefore?: number | null;
  /**
   * Categorias de inscrição com valores diferentes
   */
  registrationCategories?:
    | {
        title: string;
        /**
         * Valor em centavos (ex: R$ 100,00 = 10000)
         */
        value: number;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Descontos por quantidade de inscrições
   */
  discountGroups?:
    | {
        minQuantity: number;
        maxQuantity?: number | null;
        type: 'percentage' | 'fixed';
        /**
         * Valor do desconto
         */
        value: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Se marcado, o evento emitirá certificados
   */
  hasCertificate?: boolean | null;
  /**
   * Como os certificados serão emitidos
   */
  certificateIssuanceType?: ('manual' | 'automatic') | null;
  /**
   * Arquivo de modelo do certificado
   */
  certificateTemplate?: (number | null) | File;
  /**
   * Presença mínima para emissão de certificado
   */
  certificateIssuanceRule?: ('any' | '25%' | '50%' | '75%' | 'full') | null;
  /**
   * Programação do evento
   */
  activities: {
    title: string;
    description?: string | null;
    /**
     * Sala onde a atividade acontecerá
     */
    room: number | EventRoom;
    /**
     * Data da atividade
     */
    activityDate: string;
    /**
     * Horário de início
     */
    activityStartTime: string;
    /**
     * Horário de encerramento
     */
    activityEndTime: string;
    /**
     * Palestrantes desta atividade
     */
    speakers?: (number | Speaker)[] | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  /**
   * Nome completo
   */
  participantName: string;
  /**
   * Email para contato
   */
  participantEmail: string;
  /**
   * Telefone de contato
   */
  participantPhone: string;
  /**
   * Número da OAB (opcional)
   */
  oabNumber?: string | null;
  /**
   * Evento no qual o participante está se inscrevendo
   */
  event: number | Event;
  /**
   * Atividades que o participante deseja participar
   */
  selectedActivities: {
    /**
     * ID da atividade do evento
     */
    activityId: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'files';
        value: number | File;
      } | null)
    | ({
        relationTo: 'event-rooms';
        value: number | EventRoom;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'fileFolders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  isPublic?: T;
  createdBy?: T;
  editedBy?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rooms_select".
 */
export interface EventRoomsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  capacity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  professionalTitle?: T;
  description?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  location?: T;
  image?: T;
  modality?: T;
  scope?: T;
  startDate?: T;
  endDate?: T;
  startTime?: T;
  endTime?: T;
  registrationType?: T;
  externalRegistrationUrl?: T;
  registrationLimit?: T;
  refundDays?: T;
  registrationStart?: T;
  registrationEnd?: T;
  checkinMinutesBefore?: T;
  registrationCategories?:
    | T
    | {
        title?: T;
        value?: T;
        description?: T;
        id?: T;
      };
  discountGroups?:
    | T
    | {
        minQuantity?: T;
        maxQuantity?: T;
        type?: T;
        value?: T;
        id?: T;
      };
  hasCertificate?: T;
  certificateIssuanceType?: T;
  certificateTemplate?: T;
  certificateIssuanceRule?: T;
  activities?:
    | T
    | {
        title?: T;
        description?: T;
        room?: T;
        activityDate?: T;
        activityStartTime?: T;
        activityEndTime?: T;
        speakers?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  participantName?: T;
  participantEmail?: T;
  participantPhone?: T;
  oabNumber?: T;
  event?: T;
  selectedActivities?:
    | T
    | {
        activityId?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fileFolders_select".
 */
export interface FileFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}